name: Test Payload Woocommerce

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: install
        run: npm i
      - name: Lint CSS
        run: npm run lint:css -- src/css/
      - name: List JS
        run: npm run lint:js -- src/js/
